### ISSUE TITLE
Is Manager the right attribute to store this in?

### ISSUE THREAD

**Issue by lochiiconnectivity** [nicolonsky/AzureADGuestReview#1]
First of all, I'd like to congratulate you on this , it seems a really useful project in the absence of the Microsoft AAD Premium feature. 

I'd like to ask if the Manager attribute is the right place to be storing the "sponsor"? if you populate the manager attribute then you are creating a management hierarchy and reporting line which will show up in a bunch of office 365 applications which are rendering the directory, and it could lead to misleading results, showing that a person has reports which are external to the company. 

Is there a better place to put this in the guest account, for example, another open extension?

**Comment by nicolonsky** [comment]
@lochiiconnectivity Thank you. There's probably no one-size-fits-all solution available. You can easily adjust the solution to maintain the guest inviter within the extension attribute (the inviter UPN is already stored there).

Advantages when using the manager attribute (feedback from the field / my opinion):

* Visibility within the AAD portal for admins
* As you mentioned hierarchy can be viewed within Teams and other apps -> All users know who invited the guest and who's responsible for the account internally

Disadvantages:  

* Same as the advantages
